import type { Metadata } from "next";
import { Suspense } from "react";
import { BriefcaseBusiness, Handshake, Mail, MapPin, MessageCircle, Phone, Shapes } from "lucide-react";
import { ContactForm } from "@/components/contact/contact-form";
import { Container } from "@/components/ui/container";
import { siteConfig } from "@/config/site";
import { getDictionary } from "@/i18n/dictionaries";
import { localizePath } from "@/i18n/config";
import { getLocale } from "@/i18n/server";

export async function generateMetadata(): Promise<Metadata> { const locale = await getLocale(); return { title: locale === "id" ? "Kontak" : "Contact", description: locale === "id" ? "Hubungi Sadani untuk pertanyaan umum, kemitraan, kolaborasi produk, atau karier." : "Contact Sadani about general inquiries, partnerships, product collaboration, or future careers.", alternates: { canonical: localizePath(locale, "/contact"), languages: { id: "/contact", en: "/en/contact" } } }; }
const inquiry = [{ icon: MessageCircle, title: "General inquiries" }, { icon: Handshake, title: "Partnership" }, { icon: Shapes, title: "Product collaboration" }, { icon: BriefcaseBusiness, title: "Careers" }];
export default async function ContactPage() { const locale = await getLocale(); const dictionary = getDictionary(locale); return <><section className="page-hero"><Container><p className="eyebrow text-green">{dictionary.contact.eyebrow}</p><h1>{dictionary.contact.title}</h1><p>{dictionary.contact.copy}</p></Container></section><section className="pb-24 sm:pb-32"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><div><h2 className="text-xl font-semibold text-ink">{dictionary.contact.discuss}</h2><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-1">{inquiry.map(({ icon: Icon }, index) => <div className="inquiry-type" key={dictionary.contact.inquiry[index]}><Icon size={19} /><span>{dictionary.contact.inquiry[index]}</span></div>)}</div><div className="company-contact"><div><Mail size={18} /><p><strong>{dictionary.contact.email}</strong><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p></div><div><Phone size={18} /><p><strong>{dictionary.contact.phone}</strong><a href={`tel:${siteConfig.phone.href}`}>{siteConfig.phone.display}</a></p></div><div><MapPin size={18} /><address><strong>{dictionary.contact.location}</strong><span>{siteConfig.address.city}, {siteConfig.address.province}, {siteConfig.address.country}</span></address></div></div><p className="mt-6 text-xs leading-5 text-muted">{dictionary.contact.responseTime}</p></div><Suspense fallback={<div className="contact-form min-h-[500px] animate-pulse" />}><ContactForm locale={locale} email={siteConfig.email} /></Suspense></div></Container></section></>; }
