"use client";

import { useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle } from "lucide-react";

type FieldErrors = Partial<Record<"name" | "email" | "company" | "inquiryType" | "message", string[]>>;

export function ContactForm() {
  const params = useSearchParams(); const defaultType = params.get("type") === "career" ? "career" : "general";
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<FieldErrors>({});
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("loading"); setMessage(""); setErrors({}); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { message: string; errors?: FieldErrors }; setMessage(result.message); setErrors(result.errors || {}); setState(response.ok ? "success" : "error"); if (response.ok) form.reset(); } catch { setMessage("We couldn’t connect to the contact service. Please try again later."); setState("error"); } }
  return <form className="contact-form" onSubmit={submit} noValidate><div className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Full name" required error={errors.name?.[0]} /><Field name="email" label="Email" type="email" required error={errors.email?.[0]} /><Field name="company" label="Company / organization" hint="Optional" error={errors.company?.[0]} /><label className="field"><span>Inquiry type <b>*</b></span><select name="inquiryType" defaultValue={defaultType} required aria-invalid={Boolean(errors.inquiryType)}><option value="general">General</option><option value="partnership">Partnership</option><option value="product">Product</option><option value="career">Career</option><option value="other">Other</option></select>{errors.inquiryType?.[0] && <small className="field-error">{errors.inquiryType[0]}</small>}</label></div><label className="field mt-5"><span>Message <b>*</b></span><textarea name="message" rows={6} required minLength={20} maxLength={3000} placeholder="Tell us a little about what you have in mind." aria-invalid={Boolean(errors.message)} />{errors.message?.[0] && <small className="field-error">{errors.message[0]}</small>}</label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><div className="mt-6 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><button className="button button-primary min-w-40 justify-center" disabled={state === "loading"} type="submit">{state === "loading" ? <><LoaderCircle className="animate-spin" size={17} /> Sending…</> : <>Send inquiry <ArrowRight size={17} /></>}</button>{message && <p role="status" className={`form-status ${state === "success" ? "form-success" : "form-error"}`}>{state === "success" && <CheckCircle2 size={17} />}{message}</p>}</div><p className="mt-5 text-xs leading-5 text-muted">This form validates your message securely. Delivery remains disabled until Sadani configures an official email provider.</p></form>;
}

function Field({ name, label, type = "text", required, hint, error }: { name: string; label: string; type?: string; required?: boolean; hint?: string; error?: string }) { return <label className="field"><span>{label} {required && <b>*</b>} {hint && <small>{hint}</small>}</span><input name={name} type={type} required={required} maxLength={type === "email" ? 254 : 120} aria-invalid={Boolean(error)} />{error && <small className="field-error">{error}</small>}</label>; }
